# Generated by Django 4.1.6 on 2023-08-09 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0002_sequence_ids_and_more_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="seqhash",
        ),
        migrations.RemoveField(
            model_name="alignment",
            name="seqhash",
        ),
    ]
