# Generated by Django 4.1.6 on 2023-08-09 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0003_remove_sample_seqhash_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alignment",
            unique_together={("sequence", "element")},
        ),
    ]
