# Generated by Django 4.1.6 on 2023-08-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0004_alter_alignment_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignment",
            name="variants",
            field=models.ManyToManyField(
                related_name="alignments",
                through="rest_api.Alignment2Variant",
                to="rest_api.variant",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sequence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="samples",
                to="rest_api.sequence",
            ),
        ),
    ]
